services:
  - type: web
    name: gerenciador-receitas-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm --workspace backend start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
